name: Build with Mamba

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_conda:
    name: Build conda package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1.9.0
      with:
        micromamba-version: 'latest'
        environment-name: build-env
        create-args: >-
          python=3.12
          conda-build
          boa
          anaconda-client

    - name: Build conda package
      shell: bash -l {0}
      run: |
        conda mambabuild conda.recipe --output-folder dist/conda

    - name: Upload conda package artifacts
      uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
      with:
        name: conda-package
        path: dist/conda/**/*.tar.bz2

  upload_conda:
    needs: [build_conda]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      contents: read

    steps:
    - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
        name: conda-package
        path: dist/conda

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1.9.0
      with:
        micromamba-version: 'latest'
        environment-name: upload-env
        create-args: >-
          anaconda-client

    - name: Upload to Anaconda Cloud
      shell: bash -l {0}
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda -t $ANACONDA_TOKEN upload --user phygbu dist/conda/**/*.tar.bz2
